### ISSUE TITLE
Need Ability-UI for 6/5 lvl spells

### ISSUE THREAD

**Issue by warpdragon** [AngelArenaAllstars/oaa#90] opened 2017-02-26 14:47 UTC
# Need Ability-UI for Six-Level abilities
By default, I believe, Dota only properly displays the ability-level indicator dots (you know the ones) beneath Hero-Abilities in *odd-numbers*. Currently if you were to, say, put a six-level hero ability in AAA, it would only show the first 5 indicator dots (the sixth being hidden/invisible/just not there at all). vOLvo Pls

Need a LUA-scripting/PNG-overlay solution for displaying an even number (6) of dots beneath a spell.

**Comment by spar36** [comment] 2017-02-27 04:38
I have dont know how to do this, but could you just display the next highest odd number, so 7, and then cover up the last dot.

**Comment by yeahbuddy-dota** [comment] 2017-02-27 05:01
Aren't all normal DotA skills 4 levels.. they all show up fine

**Comment by warpdragon** [comment] 2017-02-27 05:29
No ur right it does show 4 dots fine. But nevertheless it doesnt work when u give em 6

**Comment by Trildar** [comment] 2017-02-28 13:25
This can actually be fixed with just some CSS since the UI does actually insert classes to indicate abilities of arbitrary levels. The problem is that doing it that way would require overriding one of the built-in CSS files, meaning that stuff may break if they ever change that file.

It's probably also possible to add the required style by JavaScript, which may be more resistant to breaking from changes depending on how it's done, but it's also harder.

Also, just to note, the dots have class LevelPanel and setting the left and right margins to 1px seems to produce good results.

**Comment by Trildar** [comment] 2017-03-01 17:08
On further investigation, the JavaScript method might not be at all practical as it causes lag. If anyone can think of a way that doesn't involve looping through all the dots every time the selected unit is changed, but otherwise I'll probably put in a PR to add the CSS file tomorrow.

**Closed** 2017-03-12 13:09 UTC
